/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 Intergalactic_Spaceships_Version_2.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../public/Intergalactic_Spaceships_Version_2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Intergalactic_Spaceships_Version_2" geometry={nodes.Intergalactic_Spaceships_Version_2.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]}>
          <group name="Area" position={[-2.906, -1.632, 0.485]} rotation={[3.13, 0.016, -1.266]} scale={[2.47, 1, 1]} />          <group name="Area001" position={[2.937, -1.821, 0.535]} rotation={[0.014, -0.012, -1.24]} scale={[-2.464, -0.997, -0.997]} />
          <group name="Empty" position={[-1.075, -5.542, -0.256]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.002']} position={[0.049, -0.075, 0.257]} scale={[1, 1, 1.253]} />
            <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Material.003']} position={[0.049, -0.075, -2.676]} rotation={[0, 0, -2.513]} scale={0.328} />
            <mesh name="Torus004" geometry={nodes.Torus004.geometry} material={materials['Material.003']} position={[0.049, -0.075, 0.257]} />
            <group name="Point004" position={[0.205, 0.036, -2.656]} rotation={[0.002, 0.04, -0.042]} />
            <group name="Point006" rotation={[1.571, -0.001, -0.025]} scale={4.081} />
            <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Torus002.morphTargetDictionary} morphTargetInfluences={nodes.Torus002.morphTargetInfluences} position={[0.049, -0.075, -1.698]} rotation={[0, 0, -2.513]} scale={1.077} />
            <mesh name="Torus003" geometry={nodes.Torus003.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Torus003.morphTargetDictionary} morphTargetInfluences={nodes.Torus003.morphTargetInfluences} position={[0.049, -0.075, -0.721]} rotation={[0, 0, -1.257]} scale={1.25} />
          </group>
          <group name="Empty001" position={[1.149, -5.541, -0.253]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.002']} position={[-0.116, -0.078, 0.267]} scale={[1, 1, 1.253]} />
            <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials['Material.003']} position={[-0.116, -0.078, -2.667]} rotation={[0, 0, -2.513]} scale={0.328} />
            <group name="Point003" position={[0.134, -0.14, -2.676]} rotation={[0.002, 0.04, -0.042]} />
            <group name="Point005" rotation={[1.571, -0.001, -0.025]} scale={3.739} />
            <mesh name="Torus000" geometry={nodes.Torus000.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Torus000.morphTargetDictionary} morphTargetInfluences={nodes.Torus000.morphTargetInfluences} position={[-0.116, -0.078, -3.644]} rotation={[0, 0, -1.257]} scale={0.058} />
            <mesh name="Torus005" geometry={nodes.Torus005.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Torus005.morphTargetDictionary} morphTargetInfluences={nodes.Torus005.morphTargetInfluences} position={[-0.116, -0.078, -0.711]} rotation={[0, 0, -1.257]} scale={1.25} />
            <mesh name="Torus006" geometry={nodes.Torus006.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Torus006.morphTargetDictionary} morphTargetInfluences={nodes.Torus006.morphTargetInfluences} position={[-0.116, -0.078, -1.689]} rotation={[0, 0, -2.513]} scale={1.077} />
          </group>
          <group name="Point001" position={[1.336, -1.57, 1.064]} rotation={[-1.571, 0.04, -0.001]} scale={0.607} />
          <group name="Point002" position={[-1.418, -1.572, 1.032]} rotation={[-1.571, 0.04, -0.001]} scale={0.662} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('../../public/Intergalactic_Spaceships_Version_2.glb')
